l={
errorloading:"Error when loading birth data:",
errorloading1:"Error when loading population data:",
in_:"in",
for_country:"statewide:",
date:"Date",
births:"Births",
region:"District",
to_:"to",
between_:"between",
and_:"and",
to1000people:"Monthly for every 10000 people",
years:"y.o.",
changeOld:"Change relative to ",
allbirths:"All births",
incomplete:"Data from 2011 is incomplete",
cities: [
"Pleven",
"Razgrad",
"Haskovo",
"Shumen",
"Silistra",
"Yambol",
"Veliko Tarnovo",
"Gabrovo",
"Plovdiv",
"Smolyan",
"Sofia",
"Sofia (capital)",
"Vidin",
"Vratsa",
"Kyustendil",
"Stara Zagora",
"Burgas",
"Lovech",
"Montana",
"Pazardzhik",
"Ruse",
"Targovishte",
"Blagoevgrad",
"Varna",
"Pernik",
"Sliven",
"Dobrich",
"Kardjali"
]
};
